"""
Strategy Layer - Modular Strategy Plugins

Base strategy interface and implementations:
- Triangular arbitrage
- Cross-DEX arbitrage
- Back-running
- Liquidation
- JIT Liquidity

Each strategy is a plugin that can be enabled/disabled dynamically.
"""
from abc import ABC, abstractmethod
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field
from datetime import datetime
import asyncio


@dataclass
class StrategyConfig:
    """Configuration for a strategy"""
    name: str
    enabled: bool = True
    min_profit_percent: float = 0.1
    max_capital_usd: float = 10000.0
    max_risk_percent: float = 2.0
    parameters: Dict = field(default_factory=dict)


@dataclass
class StrategySignal:
    """Signal generated by a strategy"""
    strategy_name: str
    token_path: List[str]  # e.g., [USDC, SOL, USDC]
    pool_addresses: List[str]
    direction: List[str]  # ['buy', 'sell', ...]
    expected_profit_percent: float
    expected_profit_usd: float
    required_capital_usd: float
    confidence: float  # 0.0 to 1.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    ttl_ms: int = 5000  # Time to live
    
    def is_expired(self) -> bool:
        """Check if signal has expired"""
        age_ms = (datetime.utcnow() - self.timestamp).total_seconds() * 1000
        return age_ms > self.ttl_ms
    
    def to_dict(self) -> dict:
        return {
            "strategy_name": self.strategy_name,
            "token_path": self.token_path,
            "pool_addresses": self.pool_addresses,
            "direction": self.direction,
            "expected_profit_percent": self.expected_profit_percent,
            "expected_profit_usd": self.expected_profit_usd,
            "required_capital_usd": self.required_capital_usd,
            "confidence": self.confidence,
            "timestamp": self.timestamp.isoformat(),
            "ttl_ms": self.ttl_ms,
            "expired": self.is_expired(),
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all strategies
    
    Each strategy must implement:
    - generate_signals(): Main logic to find opportunities
    - validate_signal(): Check if signal is still valid
    - get_statistics(): Performance metrics
    """
    
    def __init__(self, config: StrategyConfig):
        self.config = config
        self.enabled = config.enabled
        self.signals_generated = 0
        self.signals_executed = 0
        self.total_profit_usd = 0.0
        self.win_count = 0
        self.loss_count = 0
    
    @abstractmethod
    async def generate_signals(
        self,
        graph_data: Dict,
        market_data: Dict,
    ) -> List[StrategySignal]:
        """
        Generate trading signals based on market data
        
        Args:
            graph_data: Liquidity graph data
            market_data: Current market prices, volumes, etc.
        
        Returns:
            List of StrategySignal objects
        """
        pass
    
    @abstractmethod
    async def validate_signal(
        self,
        signal: StrategySignal,
        current_market_data: Dict,
    ) -> bool:
        """
        Validate if signal is still profitable
        
        Args:
            signal: Signal to validate
            current_market_data: Latest market data
        
        Returns:
            True if signal is still valid
        """
        pass
    
    @abstractmethod
    def get_statistics(self) -> Dict:
        """Get strategy performance statistics"""
        pass
    
    def enable(self):
        """Enable strategy"""
        self.enabled = True
    
    def disable(self):
        """Disable strategy"""
        self.enabled = False
    
    def record_execution(self, signal: StrategySignal, profit_usd: float, success: bool):
        """Record execution result for statistics"""
        self.signals_executed += 1
        self.total_profit_usd += profit_usd
        
        if success:
            self.win_count += 1
        else:
            self.loss_count += 1


class TriangularStrategy(BaseStrategy):
    """
    Triangular Arbitrage Strategy
    
    Find opportunities in triangular paths:
    A → B → C → A
    
    Example: USDC → SOL → USDC → USDC
    """
    
    def __init__(self, config: StrategyConfig = None):
        if config is None:
            config = StrategyConfig(
                name="triangular",
                enabled=True,
                min_profit_percent=0.1,
                max_capital_usd=5000.0,
            )
        super().__init__(config)
        
        self.max_hops = 3  # Triangular = 3 swaps
    
    async def generate_signals(
        self,
        graph_data: Dict,
        market_data: Dict,
    ) -> List[StrategySignal]:
        """Generate triangular arbitrage signals"""
        signals = []
        
        # Extract pools and tokens from graph data
        pools = graph_data.get("pools", {})
        tokens = graph_data.get("tokens", {})
        
        # Find triangular paths (simplified - production uses Bellman-Ford)
        for token_a in tokens:
            for token_b in tokens:
                if token_a == token_b:
                    continue
                
                for token_c in tokens:
                    if token_c in [token_a, token_b]:
                        continue
                    
                    # Check if triangular path exists
                    path = [token_a, token_b, token_c, token_a]
                    signal = await self._check_triangular_path(
                        path=path,
                        pools=pools,
                        market_data=market_data,
                    )
                    
                    if signal:
                        signals.append(signal)
                        self.signals_generated += 1
        
        return signals
    
    async def _check_triangular_path(
        self,
        path: List[str],
        pools: Dict,
        market_data: Dict,
    ) -> Optional[StrategySignal]:
        """Check if triangular path is profitable"""
        # Simplified logic - production uses full simulation
        # 1. Get prices for each leg
        # 2. Calculate output after 3 swaps
        # 3. Check if profit > min_profit_percent
        
        # Example calculation (placeholder)
        start_amount = 1000.0  # Assume $1000
        current_amount = start_amount
        
        pool_addresses = []
        directions = []
        
        for i in range(len(path) - 1):
            token_in = path[i]
            token_out = path[i + 1]
            
            # Find pool for this pair
            pool_key = f"{token_in}-{token_out}"
            if pool_key not in pools:
                return None
            
            pool = pools[pool_key]
            pool_addresses.append(pool["address"])
            directions.append("buy" if i % 2 == 0 else "sell")
            
            # Apply price and fee (simplified)
            price = pool.get("price", 1.0)
            fee = pool.get("fee_percent", 0.25) / 100
            current_amount = current_amount * price * (1 - fee)
        
        # Calculate profit
        profit_usd = current_amount - start_amount
        profit_percent = (profit_usd / start_amount) * 100
        
        # Check if profitable enough
        if profit_percent < self.config.min_profit_percent:
            return None
        
        # Create signal
        return StrategySignal(
            strategy_name=self.config.name,
            token_path=path,
            pool_addresses=pool_addresses,
            direction=directions,
            expected_profit_percent=profit_percent,
            expected_profit_usd=profit_usd,
            required_capital_usd=start_amount,
            confidence=0.8,  # Simplified
            ttl_ms=3000,  # 3 seconds TTL for triangular
        )
    
    async def validate_signal(
        self,
        signal: StrategySignal,
        current_market_data: Dict,
    ) -> bool:
        """Validate triangular signal"""
        if signal.is_expired():
            return False
        
        # Re-check profitability with current prices
        # (simplified - production uses full re-simulation)
        return signal.expected_profit_percent >= self.config.min_profit_percent
    
    def get_statistics(self) -> Dict:
        """Get strategy statistics"""
        win_rate = (
            self.win_count / (self.win_count + self.loss_count) * 100
            if (self.win_count + self.loss_count) > 0 else 0
        )
        
        return {
            "name": self.config.name,
            "enabled": self.enabled,
            "signals_generated": self.signals_generated,
            "signals_executed": self.signals_executed,
            "total_profit_usd": self.total_profit_usd,
            "win_count": self.win_count,
            "loss_count": self.loss_count,
            "win_rate": win_rate,
            "avg_profit_per_signal": (
                self.total_profit_usd / self.signals_executed
                if self.signals_executed > 0 else 0
            ),
        }


class CrossDEXStrategy(BaseStrategy):
    """
    Cross-DEX Arbitrage Strategy
    
    Find price differences between DEXes:
    Buy on Raydium, Sell on Orca
    """
    
    def __init__(self, config: StrategyConfig = None):
        if config is None:
            config = StrategyConfig(
                name="cross_dex",
                enabled=True,
                min_profit_percent=0.15,
                max_capital_usd=10000.0,
            )
        super().__init__(config)
    
    async def generate_signals(
        self,
        graph_data: Dict,
        market_data: Dict,
    ) -> List[StrategySignal]:
        """Generate cross-DEX arbitrage signals"""
        signals = []
        
        # Extract pools
        pools = graph_data.get("pools", {})
        
        # Group pools by token pair
        token_pairs: Dict[str, List] = {}
        for pool_id, pool in pools.items():
            pair_key = f"{pool['token_a']}-{pool['token_b']}"
            if pair_key not in token_pairs:
                token_pairs[pair_key] = []
            token_pairs[pair_key].append(pool)
        
        # Find price differences between DEXes
        for pair_key, pool_list in token_pairs.items():
            if len(pool_list) < 2:
                continue  # Need at least 2 pools for cross-DEX
            
            # Compare each pair of pools
            for i, pool_a in enumerate(pool_list):
                for pool_b in pool_list[i+1:]:
                    if pool_a["dex"] == pool_b["dex"]:
                        continue  # Same DEX, skip
                    
                    signal = await self._check_cross_dex_opportunity(
                        pool_a=pool_a,
                        pool_b=pool_b,
                    )
                    
                    if signal:
                        signals.append(signal)
                        self.signals_generated += 1
        
        return signals
    
    async def _check_cross_dex_opportunity(
        self,
        pool_a: Dict,
        pool_b: Dict,
    ) -> Optional[StrategySignal]:
        """Check cross-DEX opportunity"""
        # Get prices
        price_a = pool_a.get("price_a_per_b", 1.0)
        price_b = pool_b.get("price_a_per_b", 1.0)
        
        if price_a <= 0 or price_b <= 0:
            return None
        
        # Determine direction (buy low, sell high)
        if price_a < price_b:
            buy_pool, sell_pool = pool_a, pool_b
            direction = "buy_on_a_sell_on_b"
        else:
            buy_pool, sell_pool = pool_b, pool_a
            direction = "buy_on_b_sell_on_a"
        
        # Calculate profit (simplified)
        start_amount = 1000.0
        fee_a = buy_pool.get("fee_percent", 0.25) / 100
        fee_b = sell_pool.get("fee_percent", 0.25) / 100
        
        # Buy on cheaper DEX
        tokens_bought = start_amount / buy_pool["price_a_per_b"] * (1 - fee_a)
        
        # Sell on expensive DEX
        final_amount = tokens_bought * sell_pool["price_a_per_b"] * (1 - fee_b)
        
        profit_usd = final_amount - start_amount
        profit_percent = (profit_usd / start_amount) * 100
        
        if profit_percent < self.config.min_profit_percent:
            return None
        
        return StrategySignal(
            strategy_name=self.config.name,
            token_path=[buy_pool["token_a"], buy_pool["token_b"]],
            pool_addresses=[buy_pool["address"], sell_pool["address"]],
            direction=["buy", "sell"],
            expected_profit_percent=profit_percent,
            expected_profit_usd=profit_usd,
            required_capital_usd=start_amount,
            confidence=0.85,
            ttl_ms=5000,
        )
    
    async def validate_signal(
        self,
        signal: StrategySignal,
        current_market_data: Dict,
    ) -> bool:
        """Validate cross-DEX signal"""
        if signal.is_expired():
            return False
        
        return signal.expected_profit_percent >= self.config.min_profit_percent
    
    def get_statistics(self) -> Dict:
        """Get strategy statistics"""
        win_rate = (
            self.win_count / (self.win_count + self.loss_count) * 100
            if (self.win_count + self.loss_count) > 0 else 0
        )
        
        return {
            "name": self.config.name,
            "enabled": self.enabled,
            "signals_generated": self.signals_generated,
            "signals_executed": self.signals_executed,
            "total_profit_usd": self.total_profit_usd,
            "win_count": self.win_count,
            "loss_count": self.loss_count,
            "win_rate": win_rate,
            "avg_profit_per_signal": (
                self.total_profit_usd / self.signals_executed
                if self.signals_executed > 0 else 0
            ),
        }


class StrategyManager:
    """
    Manager for all strategies
    
    - Enable/disable strategies dynamically
    - Collect signals from all strategies
    - Aggregate and prioritize signals
    """
    
    def __init__(self):
        self.strategies: Dict[str, BaseStrategy] = {}
        self.configs: Dict[str, StrategyConfig] = {}
    
    def register_strategy(self, strategy: BaseStrategy):
        """Register a strategy"""
        self.strategies[strategy.config.name] = strategy
        self.configs[strategy.config.name] = strategy.config
    
    def unregister_strategy(self, strategy_name: str):
        """Unregister a strategy"""
        if strategy_name in self.strategies:
            del self.strategies[strategy_name]
            del self.configs[strategy_name]
    
    def enable_strategy(self, strategy_name: str):
        """Enable a strategy"""
        if strategy_name in self.strategies:
            self.strategies[strategy_name].enable()
    
    def disable_strategy(self, strategy_name: str):
        """Disable a strategy"""
        if strategy_name in self.strategies:
            self.strategies[strategy_name].disable()
    
    async def collect_all_signals(
        self,
        graph_data: Dict,
        market_data: Dict,
    ) -> List[StrategySignal]:
        """Collect signals from all enabled strategies"""
        all_signals = []
        
        for strategy in self.strategies.values():
            if not strategy.enabled:
                continue
            
            try:
                signals = await strategy.generate_signals(graph_data, market_data)
                all_signals.extend(signals)
            except Exception as e:
                print(f"Error in strategy {strategy.config.name}: {e}")
        
        # Sort by confidence and profit
        all_signals.sort(
            key=lambda s: (s.confidence * s.expected_profit_usd),
            reverse=True
        )
        
        return all_signals
    
    def get_all_statistics(self) -> Dict:
        """Get statistics from all strategies"""
        stats = {}
        
        for name, strategy in self.strategies.items():
            stats[name] = strategy.get_statistics()
        
        return stats
